version: 0.1
phases:
  install:
    commands:
      - pip install --upgrade awscli
      - aws --version
      - pip install panda3d
      - pip install -r requirements.txt
  build:
    commands:
      - echo Data build started on `date`
      - echo Packing Multifiles...
      - mkdir output/
      - multify -c -f output/pack_test.mf -v data/pack_test/
      - multify -c -f output/pack_test2.mf -v data/pack_test2/ 
artifacts:
  files:
    - '**/*'
  base-directory: 'output'